CREATE TABLE IF NOT EXISTS "channels" (
    id BIGSERIAL CONSTRAINT channel_pk PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1
);